services:
  qdrant:
    image: qdrant/qdrant:v1.11.3
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      QDRANT__STORAGE__STORAGE_PATH: /qdrant/storage
      QDRANT__SERVICE__GRPC_PORT: 6334

  app:
    build: .
    container_name: dicionario_vetorial_app
    ports:
      - "9000:9000"
    depends_on:
      - qdrant
    volumes:
      - .:/app
    working_dir: /app
    command: uvicorn api.dicionarioAPI:app --host 0.0.0.0 --port 9000 --reload
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333

volumes:
  qdrant_storage:
